{
    first: country(code: "fr") {code, name}
    second: country(code: "jp") {code}
    third: country(code: "up") {code}
    fourth: country(code: "en") {code}
    fifth: country(code: "to") {name}
    sixth: country(code: "pl") {name}
}
